import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Home!</h1>
				<Link href="/about" className={styles.link}>
					<span>go to</span>
					<span className={styles.link_btn}>About </span>
					<span>page</span>
				</Link>
			</main>
		</div>
	);
}
